### ISSUE TITLE
llm.cmd never responds

### ISSUE THREAD

**Issue by felixwoestmann** [simonw/llm-cmd#9]
Hello, 
I was trying out the `llm` tool and `llm-cmd` today. 

I provided my OpenAI Api key and can use `llm` as intended.
However llm-cmd does not seem to work, when I execute it (like with the example of undoing the last git commit) it gets stuck and never returns the result.

Is there a verbose option I can trigger for more debug info?

System: MacOS with zsh

**Comment by jkseppan** [comment]
Could be the same as #3 - Apple doesn't ship GNU Readline but the not-quite-compatible libedit, and depending on how your Python was compiled it might be using the latter. If you install the plugin from the main branch, it uses prompt_toolkit instead.
